# Generated by Django 3.0.4 on 2020-05-22 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_orders_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='ref_code',
            field=models.CharField(default=123, max_length=20),
            preserve_default=False,
        ),
    ]
