# Generated by Django 2.2 on 2020-07-03 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_auto_20200703_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Textile', 'Textile'), ('Handicraft', 'Handicraft')], default='Textile', max_length=50),
        ),
    ]
